### ISSUE TITLE
when i built the code,it say:Could NOT find ERPC (missing: ERPC_GEN_EXECUTABLE erpcgen erpcsniffer)

### ISSUE THREAD

**Issue by Kingwulin** [Kerr-srl/erpc-esp#1]

**Comment by Kingwulin** [comment]
would you tell me how to solve it.thanks!

**Comment by chenlijun99** [comment]
Hi @Kingwulin. Thank you for your interest in this repository! Sorry for the late reply. I was busy with work.

I've updated the documentation. In particolar you can check this README https://github.com/Kerr-srl/erpc-esp/tree/dev/src/components/erpc#erpc (which will actually tell you to follow the eRPC's documentation on how to build `erpcgen`). Once you have `erpcgen` in the PATH, it should be ok.

**Comment by Kingwulin** [comment]
Thanks for your reply,I had solve it 
I have another question about that how can I comunication between two esp32 borad

**Comment by chenlijun99** [comment]
> Thanks for your reply,I had solve it I have another question about that how can I comunication between two esp32 borad

Thanks for opening #2. I'll respond there.
